/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ShelfRouteImport } from './routes/shelf'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'
import { Route as ReadBookIdRouteImport } from './routes/read.$bookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelfRoute = ShelfRouteImport.update({
  id: '/shelf',
  path: '/shelf',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadBookIdRoute = ReadBookIdRouteImport.update({
  id: '/read/$bookId',
  path: '/read/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/shelf': typeof ShelfRoute
  '/upload': typeof UploadRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/shelf': typeof ShelfRoute
  '/upload': typeof UploadRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/shelf': typeof ShelfRoute
  '/upload': typeof UploadRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/library' | '/shelf' | '/upload' | '/book/$bookId' | '/read/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/library' | '/shelf' | '/upload' | '/book/$bookId' | '/read/$bookId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/shelf'
    | '/upload'
    | '/book/$bookId'
    | '/read/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  ShelfRoute: typeof ShelfRoute
  UploadRoute: typeof UploadRoute
  BookBookIdRoute: typeof BookBookIdRoute
  ReadBookIdRoute: typeof ReadBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelf': {
      id: '/shelf'
      path: '/shelf'
      fullPath: '/shelf'
      preLoaderRoute: typeof ShelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$bookId': {
      id: '/read/$bookId'
      path: '/read/$bookId'
      fullPath: '/read/$bookId'
      preLoaderRoute: typeof ReadBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  ShelfRoute: ShelfRoute,
  UploadRoute: UploadRoute,
  BookBookIdRoute: BookBookIdRoute,
  ReadBookIdRoute: ReadBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
