/**
 * 扩展公版书目（较完整章节，供书城）
 * 全部为公共领域作品节选/全文短篇
 */
import type { Book, Chapter } from "./types";

function ch(id: string, title: string, paragraphs: string[]): Chapter {
  return { id, title, content: paragraphs.join("\n\n") };
}

const PD = {
  visibility: "public_domain" as const,
  source: "market" as const,
  format: "text" as const,
  license: "公版 · Public Domain",
};

export const EXTRA_MARKET_BOOKS: Book[] = [
  {
    id: "pd_sanzijing",
    title: "三字经",
    author: "王应麟（题）",
    description:
      "蒙学经典全文结构。三字一句，便于记诵。属公共领域。",
    coverColor: "#3a2818",
    coverText: "三字",
    category: "历史",
    ...PD,
    licenseNote: "传统蒙学 · 公版",
    tags: ["公版", "蒙学", "国学"],
    rating: 4.8,
    readers: 1100000,
    wordCount: 5000,
    chapters: [
      ch("sz1", "人之初", [
        "人之初，性本善。性相近，习相远。苟不教，性乃迁。教之道，贵以专。",
        "昔孟母，择邻处。子不学，断机杼。窦燕山，有义方。教五子，名俱扬。",
        "养不教，父之过。教不严，师之惰。子不学，非所宜。幼不学，老何为。",
      ]),
      ch("sz2", "玉不琢", [
        "玉不琢，不成器。人不学，不知义。为人子，方少时。亲师友，习礼仪。",
        "香九龄，能温席。孝于亲，所当执。融四岁，能让梨。弟于长，宜先知。",
        "首孝弟，次见闻。知某数，识某文。一而十，十而百。百而千，千而万。",
      ]),
      ch("sz3", "三才与三光", [
        "三才者，天地人。三光者，日月星。三纲者，君臣义。父子亲，夫妇顺。",
        "曰春夏，曰秋冬。此四时，运不穷。曰南北，曰西东。此四方，应乎中。",
      ]),
    ],
    createdAt: Date.UTC(2020, 1, 1),
  },
  {
    id: "pd_daxue",
    title: "大学（全文）",
    author: "曾子（传）· 朱熹章句本传统白文",
    description: "四书之一。明明德、亲民、止于至善。公版经籍。",
    coverColor: "#1c2a24",
    coverText: "大学",
    category: "社科",
    ...PD,
    licenseNote: "先秦儒家 · 公版",
    tags: ["公版", "四书", "儒家"],
    rating: 4.9,
    readers: 880000,
    wordCount: 4000,
    chapters: [
      ch("dx1", "经一章", [
        "大学之道，在明明德，在亲民，在止于至善。知止而后有定，定而后能静，静而后能安，安而后能虑，虑而后能得。",
        "物有本末，事有终始，知所先后，则近道矣。",
        "古之欲明明德于天下者，先治其国；欲治其国者，先齐其家；欲齐其家者，先修其身；欲修其身者，先正其心；欲正其心者，先诚其意；欲诚其意者，先致其知；致知在格物。",
        "物格而后知至，知至而后意诚，意诚而后心正，心正而后身修，身修而后家齐，家齐而后国治，国治而后天下平。",
        "自天子以至于庶人，壹是皆以修身为本。其本乱而末治者否矣。其所厚者薄，而其所薄者厚，未之有也。",
      ]),
      ch("dx2", "传 · 释明明德", [
        "康诰曰：「克明德。」大甲曰：「顾諟天之明命。」帝典曰：「克明峻德。」皆自明也。",
      ]),
      ch("dx3", "传 · 释新民", [
        "汤之盘铭曰：「苟日新，日日新，又日新。」康诰曰：「作新民。」诗曰：「周虽旧邦，其命惟新。」是故君子无所不用其极。",
      ]),
    ],
    createdAt: Date.UTC(2020, 1, 2),
  },
  {
    id: "pd_shijing",
    title: "诗经 · 国风选",
    author: "先秦 · 佚名",
    description: "风、雅、颂之「风」部名篇。关雎、蒹葭、桃夭等。公版。",
    coverColor: "#2a3820",
    coverText: "诗经",
    category: "文学",
    ...PD,
    licenseNote: "先秦诗歌 · 公版",
    tags: ["公版", "诗词", "国风"],
    rating: 4.9,
    readers: 1300000,
    wordCount: 6000,
    chapters: [
      ch("sj1", "周南 · 关雎", [
        "关关雎鸠，在河之洲。窈窕淑女，君子好逑。",
        "参差荇菜，左右流之。窈窕淑女，寤寐求之。",
        "求之不得，寤寐思服。悠哉悠哉，辗转反侧。",
        "参差荇菜，左右采之。窈窕淑女，琴瑟友之。",
        "参差荇菜，左右芼之。窈窕淑女，钟鼓乐之。",
      ]),
      ch("sj2", "秦风 · 蒹葭", [
        "蒹葭苍苍，白露为霜。所谓伊人，在水一方。",
        "溯洄从之，道阻且长。溯游从之，宛在水中央。",
        "蒹葭萋萋，白露未晞。所谓伊人，在水之湄。",
        "溯洄从之，道阻且跻。溯游从之，宛在水中坻。",
        "蒹葭采采，白露未已。所谓伊人，在水之涘。",
        "溯洄从之，道阻且右。溯游从之，宛在水中沚。",
      ]),
      ch("sj3", "周南 · 桃夭", [
        "桃之夭夭，灼灼其华。之子于归，宜其室家。",
        "桃之夭夭，有蕡其实。之子于归，宜其家室。",
        "桃之夭夭，其叶蓁蓁。之子于归，宜其家人。",
      ]),
      ch("sj4", "邶风 · 击鼓", [
        "击鼓其镗，踊跃用兵。土国城漕，我独南行。",
        "从孙子仲，平陈与宋。不我以归，忧心有忡。",
        "爰居爰处？爰丧其马？于以求之？于林之下。",
        "死生契阔，与子成说。执子之手，与子偕老。",
        "于嗟阔兮，不我活兮。于嗟洵兮，不我信兮。",
      ]),
    ],
    createdAt: Date.UTC(2020, 1, 3),
  },
  {
    id: "pd_zhuangzi",
    title: "庄子 · 内篇选",
    author: "庄周",
    description: "逍遥游、齐物论节选。道家经典，公共领域。",
    coverColor: "#243028",
    coverText: "庄子",
    category: "社科",
    ...PD,
    licenseNote: "战国 · 公版",
    tags: ["公版", "道家", "哲学"],
    rating: 4.8,
    readers: 720000,
    wordCount: 9000,
    chapters: [
      ch("zz1", "逍遥游（节选）", [
        "北冥有鱼，其名为鲲。鲲之大，不知其几千里也。化而为鸟，其名为鹏。鹏之背，不知其几千里也；怒而飞，其翼若垂天之云。",
        "是鸟也，海运则将徙于南冥。南冥者，天池也。",
        "齐谐者，志怪者也。谐之言曰：「鹏之徙于南冥也，水击三千里，抟扶摇而上者九万里，去以六月息者也。」",
        "且夫水之积也不厚，则其负大舟也无力。覆杯水于坳堂之上，则芥为之舟；置杯焉则胶，水浅而舟大也。",
        "风之积也不厚，则其负大翼也无力。故九万里，则风斯在下矣，而后乃今培风；背负青天，而莫之夭阏者，而后乃今将图南。",
      ]),
      ch("zz2", "齐物论（节选）", [
        "南郭子綦隐机而坐，仰天而嘘，嗒焉似丧其耦。颜成子游立侍乎前，曰：「何居乎？形固可使如槁木，而心固可使如死灰乎？今之隐机者，非昔之隐机者也。」",
        "子綦曰：「偃，不亦善乎，而问之也！今者吾丧我，汝知之乎？女闻人籁而未闻地籁，女闻地籁而未闻天籁夫！」",
        "子游曰：「敢问其方。」子綦曰：「夫大块噫气，其名为风。是唯无作，作则万窍怒呺。而独不闻之翏翏乎？」",
      ]),
    ],
    createdAt: Date.UTC(2020, 1, 4),
  },
  {
    id: "pd_taohuayuan",
    title: "桃花源记 · 归去来兮辞",
    author: "陶渊明",
    description: "东晋散文名篇合集。公版。",
    coverColor: "#2e3a28",
    coverText: "桃源",
    category: "文学",
    ...PD,
    licenseNote: "东晋 · 公版",
    tags: ["公版", "古文", "田园"],
    rating: 4.9,
    readers: 950000,
    wordCount: 3500,
    chapters: [
      ch("ty1", "桃花源记", [
        "晋太元中，武陵人捕鱼为业。缘溪行，忘路之远近。忽逢桃花林，夹岸数百步，中无杂树，芳草鲜美，落英缤纷。渔人甚异之，复前行，欲穷其林。",
        "林尽水源，便得一山，山有小口，仿佛若有光。便舍船，从口入。初极狭，才通人。复行数十步，豁然开朗。土地平旷，屋舍俨然，有良田美池桑竹之属。阡陌交通，鸡犬相闻。",
        "其中往来种作，男女衣着，悉如外人。黄发垂髫，并怡然自乐。",
        "见渔人，乃大惊，问所从来。具答之。便要还家，设酒杀鸡作食。村中闻有此人，咸来问讯。自云先世避秦时乱，率妻子邑人来此绝境，不复出焉，遂与外人间隔。问今是何世，乃不知有汉，无论魏晋。",
        "此人一一为具言所闻，皆叹惋。余人各复延至其家，皆出酒食。停数日，辞去。此中人语云：「不足为外人道也。」",
        "既出，得其船，便扶向路，处处志之。及郡下，诣太守，说如此。太守即遣人随其往，寻向所志，遂迷，不复得路。",
        "南阳刘子骥，高尚士也，闻之，欣然规往。未果，寻病终。后遂无问津者。",
      ]),
      ch("ty2", "归去来兮辞（并序节选）", [
        "归去来兮，田园将芜胡不归？既自以心为形役，奚惆怅而独悲？悟已往之不谏，知来者之可追。实迷途其未远，觉今是而昨非。",
        "舟遥遥以轻飏，风飘飘而吹衣。问征夫以前路，恨晨光之熹微。",
        "乃瞻衡宇，载欣载奔。僮仆欢迎，稚子候门。三径就荒，松菊犹存。携幼入室，有酒盈樽。",
        "引壶觞以自酌，眄庭柯以怡颜。倚南窗以寄傲，审容膝之易安。园日涉以成趣，门虽设而常关。",
      ]),
    ],
    createdAt: Date.UTC(2020, 1, 5),
  },
  {
    id: "pd_liji_xueji",
    title: "礼记 · 学记",
    author: "戴圣（传）",
    description: "中国最早系统论述教育与教学的专篇。公版。",
    coverColor: "#32281c",
    coverText: "学记",
    category: "历史",
    ...PD,
    licenseNote: "汉代传经 · 公版",
    tags: ["公版", "教育", "礼"],
    rating: 4.7,
    readers: 410000,
    wordCount: 4500,
    chapters: [
      ch("xj1", "学记（上）", [
        "发虑宪，求善良，足以謏闻，不足以动众。就贤体远，足以动众，未足以化民。君子如欲化民成俗，其必由学乎！",
        "玉不琢，不成器；人不学，不知道。是故古之王者建国君民，教学为先。",
        "虽有嘉肴，弗食，不知其旨也；虽有至道，弗学，不知其善也。是故学然后知不足，教然后知困。知不足，然后能自反也；知困，然后能自强也。故曰：教学相长也。",
      ]),
      ch("xj2", "学记（中）", [
        "古之教者，家有塾，党有庠，术有序，国有学。比年入学，中年考校。一年视离经辨志，三年视敬业乐群，五年视博习亲师，七年视论学取友，谓之小成。九年知类通达，强立而不反，谓之大成。",
        "大学始教，皮弁祭菜，示敬道也。宵雅肄三，官其始也。入学鼓箧，孙其业也。夏楚二物，收其威也。",
      ]),
      ch("xj3", "学记（下）", [
        "大学之教也，时教必有正业，退息必有居学。不学操缦，不能安弦；不学博依，不能安诗；不学杂服，不能安礼。不兴其艺，不能乐学。",
        "故君子之于学也，藏焉修焉，息焉游焉。夫然，故安其学而亲其师，乐其友而信其道，是以虽离师辅而不反也。",
      ]),
    ],
    createdAt: Date.UTC(2020, 1, 6),
  },
  {
    id: "pd_shakespeare_sonnets",
    title: "Shakespeare’s Sonnets（selected）",
    author: "William Shakespeare",
    description:
      "Public domain sonnets 18, 29, 116. English classic for bilingual reading.",
    coverColor: "#1a2430",
    coverText: "Sonnet",
    category: "文学",
    ...PD,
    licenseNote: "Pre-1929 English · Public Domain",
    tags: ["公版", "English", "诗"],
    rating: 4.8,
    readers: 1500000,
    wordCount: 2500,
    chapters: [
      ch("ss18", "Sonnet 18", [
        "Shall I compare thee to a summer’s day? Thou art more lovely and more temperate:",
        "Rough winds do shake the darling buds of May, And summer’s lease hath all too short a date;",
        "Sometime too hot the eye of heaven shines, And often is his gold complexion dimm’d;",
        "And every fair from fair sometime declines, By chance or nature’s changing course untrimm’d;",
        "But thy eternal summer shall not fade, Nor lose possession of that fair thou ow’st;",
        "Nor shall death brag thou wander’st in his shade, When in eternal lines to time thou grow’st:",
        "So long as men can breathe or eyes can see, So long lives this, and this gives life to thee.",
      ]),
      ch("ss29", "Sonnet 29", [
        "When, in disgrace with fortune and men’s eyes, I all alone beweep my outcast state,",
        "And trouble deaf heaven with my bootless cries, And look upon myself and curse my fate,",
        "Wishing me like to one more rich in hope, Featured like him, like him with friends possess’d,",
        "Desiring this man’s art and that man’s scope, With what I most enjoy contented least;",
        "Yet in these thoughts myself almost despising, Haply I think on thee, and then my state,",
        "Like to the lark at break of day arising From sullen earth, sings hymns at heaven’s gate;",
        "For thy sweet love remember’d such wealth brings That then I scorn to change my state with kings.",
      ]),
      ch("ss116", "Sonnet 116", [
        "Let me not to the marriage of true minds Admit impediments. Love is not love",
        "Which alters when it alteration finds, Or bends with the remover to remove:",
        "O no; it is an ever-fixed mark, That looks on tempests, and is never shaken;",
        "It is the star to every wandering bark, Whose worth’s unknown, although his height be taken.",
        "Love’s not Time’s fool, though rosy lips and cheeks Within his bending sickle’s compass come;",
        "Love alters not with his brief hours and weeks, But bears it out even to the edge of doom.",
        "If this be error and upon me proved, I never writ, nor no man ever loved.",
      ]),
    ],
    createdAt: Date.UTC(2020, 1, 7),
  },
  {
    id: "pd_aesop",
    title: "Aesop’s Fables（selected）",
    author: "Aesop",
    description: "Classic public-domain fables in English.",
    coverColor: "#2c2418",
    coverText: "Aesop",
    category: "幻想",
    ...PD,
    licenseNote: "Ancient / traditional English translations · Public Domain",
    tags: ["公版", "English", "寓言"],
    rating: 4.6,
    readers: 2000000,
    wordCount: 4000,
    chapters: [
      ch("ae1", "The Fox and the Grapes", [
        "A famished Fox saw some clusters of ripe black grapes hanging from a trellised vine. She resorted to all her tricks to get at them, but wearied herself in vain, for she could not reach them.",
        "At last she turned away, hiding her disappointment and saying: “The Grapes are sour, and not ripe as I thought.”",
      ]),
      ch("ae2", "The Tortoise and the Hare", [
        "A Hare one day ridiculed the short feet and slow pace of the Tortoise. The latter, laughing, said: “Though you be swift as the wind, I will beat you in a race.”",
        "The Hare, deeming her assertion to be simply impossible, assented to the proposal; and they agreed that the Fox should choose the course and fix the goal.",
        "On the day appointed for the race they started together. The Tortoise never for a moment stopped, but went on with a slow but steady pace straight to the end of the course.",
        "The Hare, trusting to his native swiftness, cared little about the race, and lying down by the wayside, fell fast asleep. At last waking up, and moving as fast as he could, he saw the Tortoise had reached the goal, and was comfortably dozing after her fatigue.",
      ]),
      ch("ae3", "The Crow and the Pitcher", [
        "A Crow perishing with thirst saw a pitcher, and hoping to find water, flew to it with delight. When he reached it, he discovered to his grief that it contained so little water that he could not possibly get at it.",
        "He tried everything he could think of to reach the water, but all his efforts were in vain. At last he collected as many stones as he could carry and dropped them one by one with his beak into the pitcher, until he brought the water within his reach and thus saved his life.",
      ]),
    ],
    createdAt: Date.UTC(2020, 1, 8),
  },
];
